version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: jenkins
    ports:
      - 8083:8080
      - 50003:50000
    container_name: jenkins
    volumes:
      - ~/jenkins-home:/var/jenkins_home
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock